### ISSUE TITLE
Does not work on 1.21

### ISSUE THREAD

**Issue by PhantomRuffy** [ExternalTime/QuickCommands#1]
Can you please make this mod available for 1.21?

**Comment by ExternalTime** [comment]
Sure. Done.

**Comment by PhantomRuffy** [comment]
I still get the same error unfortunately:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Quick Commands' (quickcommands) 1.0.0 with any version that is compatible with:
		 - fabricloader 0.16.2
		 - minecraft 1.21
More details:
	 - Mod 'Quick Commands' (quickcommands) 1.0.0 requires version 0.16.5 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.16.2!
	 - Mod 'Quick Commands' (quickcommands) 1.0.0 requires version 1.21.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
